services:
  - type: web
    name: gameshelf-api
    env: node
    region: oregon
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        scope: all
        value: production
      - key: PORT
        scope: all
        value: 10000
